/** Villa Augflor — room-organised gallery (updated May 2026) */
window.VILLA_GALLERY = [
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0122.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/57e54e80-bbc5-45d9-928b-6b0ffca182d2.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0007.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0012.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0056.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0095.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0099.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0100.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0132.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/pool-area-4.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/pool-area-5.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/pool-area.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/pool-at-night.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/sunset-by-the-pool.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/garden-dining-patio.jpg", alt: "Outdoor dining at Villa Augflor", title: "Outdoor dining at Villa Augflor", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/exterior-terrace-lounge-roses.jpg", alt: "Terrace lounge at Villa Augflor", title: "Terrace lounge at Villa Augflor", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/coffee-table-sunset.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/outdooe-dining-area.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/outdoor-coffee-table.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/outdoor-dining-area.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/outdoor-patio.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-stone-house-blue-gate-number-26.jpg", alt: "Villa Augflor exterior, Cagnes-sur-Mer", title: "Villa Augflor exterior, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/entrance-gate-cypress.jpg", alt: "Wrought iron entrance gate, Villa Augflor", title: "Wrought iron entrance gate, Villa Augflor", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/terrace-hillside-view-sunset.jpg", alt: "Terrace hillside view at sunset, Villa Augflor", title: "Terrace hillside view at sunset, Villa Augflor", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/apricot-tree.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0018.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0046.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0047.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0049.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0050.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0051.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0052.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0054.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0090.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0091.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0092.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0093.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0094.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0103.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0104.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0105.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0108.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0119.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0120.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0127.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0128.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
  { room: "living", src: "assets/photos/optimized/living-room-3.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "living", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0005.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "living", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0024.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "living", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0058.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "living", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0060.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "living", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0085.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "living", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0087.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "living", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0088.jpg", alt: "Living room at Villa Augflor, French Riviera", title: "Living room at Villa Augflor, French Riviera", meta: "" },
  { room: "kitchen", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0006.jpg", alt: "Kitchen at Villa Augflor", title: "Kitchen at Villa Augflor", meta: "" },
  { room: "kitchen", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0086.jpg", alt: "Kitchen at Villa Augflor", title: "Kitchen at Villa Augflor", meta: "" },
  { room: "garden-room", src: "assets/photos/optimized/garden-room.jpg", alt: "Garden room floral display at Villa Augflor", title: "Garden room floral display at Villa Augflor", meta: "" },
  { room: "garden-room", src: "assets/photos/optimized/ground-floor-garden-room.jpg", alt: "Garden room with piano and pool view at Villa Augflor", title: "Garden room with piano and pool view at Villa Augflor", meta: "" },
  { room: "garden-room", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0004.jpg", alt: "Garden room at Villa Augflor with pool access", title: "Garden room at Villa Augflor with pool access", meta: "" },
  { room: "garden-room", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0070.jpg", alt: "Garden room at Villa Augflor with pool access", title: "Garden room at Villa Augflor with pool access", meta: "" },
  { room: "garden-room", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0071.jpg", alt: "Garden room at Villa Augflor with pool access", title: "Garden room at Villa Augflor with pool access", meta: "" },
  { room: "garden-room", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0113.jpg", alt: "Garden room at Villa Augflor with pool access", title: "Garden room at Villa Augflor with pool access", meta: "" },
  { room: "provance", src: "assets/photos/optimized/ground-floor-le-provance-bedroom.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/ground-floor-bedroom-le-provance.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/ground-floor-bedroom.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0028.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0061.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0063.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0064.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0066.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0067.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0114.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0115.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0117.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "provance", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0118.jpg", alt: "Provence ground-floor bedroom at Villa Augflor", title: "Provence ground-floor bedroom at Villa Augflor", meta: "" },
  { room: "barcelona", src: "assets/photos/optimized/master-bedroom-barcelona-2.jpg", alt: "Barcelona master bedroom at Villa Augflor", title: "Barcelona master bedroom at Villa Augflor", meta: "" },
  { room: "barcelona", src: "assets/photos/optimized/master-bedroom-barcelona.jpg", alt: "Barcelona master bedroom at Villa Augflor", title: "Barcelona master bedroom at Villa Augflor", meta: "" },
  { room: "barcelona", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0039.jpg", alt: "Barcelona master bedroom at Villa Augflor", title: "Barcelona master bedroom at Villa Augflor", meta: "" },
  { room: "barcelona", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0078.jpg", alt: "Barcelona master bedroom at Villa Augflor", title: "Barcelona master bedroom at Villa Augflor", meta: "" },
  { room: "barcelona", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0079.jpg", alt: "Barcelona master bedroom at Villa Augflor", title: "Barcelona master bedroom at Villa Augflor", meta: "" },
  { room: "barcelona", src: "assets/photos/optimized/upstairs-master-bedroom-barcelona.jpg", alt: "Barcelona master bedroom at Villa Augflor", title: "Barcelona master bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0034.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0035.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0043.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0044.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0045.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0083.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0084.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "asian", src: "assets/photos/optimized/upstairs-asian-bedroom.jpg", alt: "Asian double bedroom at Villa Augflor", title: "Asian double bedroom at Villa Augflor", meta: "" },
  { room: "bathrooms-ground", src: "assets/photos/optimized/ground-floor-bathroom.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-ground", src: "assets/photos/optimized/photo-bathroom-interior-shower-led-niches.jpg", alt: "LED shower niches", title: "LED shower niches", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0009.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0010.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0014.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0015.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0016.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0033.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0080.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0081.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "bathrooms-upstairs", src: "assets/photos/optimized/photo-villa-augflor-cagnes-sur-mer-0082.jpg", alt: "Bathroom at Villa Augflor", title: "Bathroom at Villa Augflor", meta: "" },
  { room: "exterior", src: "assets/photos/optimized/outdoor-parking.jpg", alt: "Villa Augflor private pool and garden, Cagnes-sur-Mer", title: "Villa Augflor private pool and garden, Cagnes-sur-Mer", meta: "" },
];

window.GALLERY_ROOMS = [
  { id: "all", label: "All photos" },
  { id: "exterior", label: "Pool & garden" },
  { id: "barcelona", label: "Barcelona suite" },
  { id: "asian", label: "Asian room" },
  { id: "provance", label: "Provence bedroom" },
  { id: "living", label: "Living room" },
  { id: "garden-room", label: "Garden room" },
  { id: "bathrooms", label: "Bathrooms" },
  { id: "kitchen", label: "Kitchen" },
];
