/** Villa Augflor — room-organised gallery (used on unified homepage) */
window.VILLA_GALLERY = [
  { room: "all", src: "assets/photos/optimized/photo-swimming-pool-backyard-garden-lounge.jpg", alt: "Private pool with Mediterranean garden lounge", title: "Pool & garden", meta: "Exterior · signature view" },
  { room: "exterior", src: "assets/photos/optimized/photo-pool-sunset-evening-view.jpg", alt: "Pool at sunset with hillside view", title: "Pool at sunset", meta: "Exterior · golden hour" },
  { room: "exterior", src: "assets/photos/optimized/swimming-pool.jpg", alt: "Swimming pool with lounge area", title: "Pool terrace", meta: "Exterior · sun loungers" },
  { room: "exterior", src: "assets/photos/optimized/pool-patio-yellow-awning.jpg", alt: "Pool patio with yellow sun awning", title: "Pool patio", meta: "Exterior · 2025 photo" },
  { room: "exterior", src: "assets/photos/optimized/garden-dining-patio.jpg", alt: "Outdoor dining pergola with grape vines", title: "Pergola dining", meta: "Exterior · al fresco" },
  { room: "exterior", src: "assets/photos/optimized/entrance-gate-cypress.jpg", alt: "Wrought iron entrance gate with cypress trees", title: "Entrance gate", meta: "Exterior · arrival" },
  { room: "exterior", src: "assets/photos/optimized/photo-villa-exterior-entrance.jpg", alt: "Villa stone facade and entrance", title: "Villa facade", meta: "Exterior · stone house" },
  { room: "exterior", src: "assets/photos/optimized/garden-archway-path.jpg", alt: "Garden path through rose archway", title: "Garden archway", meta: "Exterior · hydrangeas" },
  { room: "exterior", src: "assets/photos/optimized/exterior-terrace-lounge-roses.jpg", alt: "Shaded terrace lounge with climbing roses", title: "Terrace lounge", meta: "Exterior · roses" },
  { room: "exterior", src: "assets/photos/optimized/terrace-hillside-view-sunset.jpg", alt: "Balcony overlooking Côte d'Azur at sunset", title: "Hillside terrace", meta: "Exterior · panorama" },
  { room: "exterior", src: "assets/photos/optimized/photo-house-swimming-pool-night.jpg", alt: "Pool and villa at night", title: "Pool at night", meta: "Exterior · ambient light" },
  { room: "barcelona", src: "assets/photos/optimized/upstairs-master-bedroom-3.jpg", alt: "Barcelona master bedroom with green marble wall", title: "Master suite", meta: "Upstairs · Barcelona" },
  { room: "barcelona", src: "assets/photos/optimized/upstairs-master-bedroom-2.jpg", alt: "Barcelona master bedroom with freestanding tub", title: "Bed & en-suite tub", meta: "Upstairs · loft beams" },
  { room: "barcelona", src: "assets/photos/optimized/master-bedroom-barcelona-chairs.jpg", alt: "Barcelona master bedroom velvet chairs", title: "Bedroom seating", meta: "Upstairs · 2025 photo" },
  { room: "barcelona", src: "assets/photos/optimized/master-bedroom-c.jpg", alt: "Barcelona master dressing area", title: "Dressing corner", meta: "Upstairs · vanity" },
  { room: "asian", src: "assets/photos/optimized/upstairs-double-bedroom.jpg", alt: "Asian double bedroom with peacock motifs", title: "Double bed", meta: "Upstairs · Asian room" },
  { room: "asian", src: "assets/photos/optimized/asian-room-console.jpg", alt: "Asian bedroom console with bamboo lantern", title: "Console & lantern", meta: "Upstairs · decor" },
  { room: "asian", src: "assets/photos/optimized/asian-room-decor.jpg", alt: "Asian bedroom with orchids and birdcage accents", title: "Decor detail", meta: "Upstairs · orchids" },
  { room: "provance", src: "assets/photos/optimized/ground-floor-bedroom-3.jpg", alt: "Provence bedroom with marble accent wall", title: "Full room view", meta: "Ground floor · Provence" },
  { room: "provance", src: "assets/photos/optimized/photo-bedroom-canopy-bed-with-teddy-bear.jpg", alt: "Provence bedroom with canopy net and vintage mirrors", title: "Canopy bed", meta: "Ground floor · romantic" },
  { room: "provance", src: "assets/photos/optimized/ground-floor-bedroom.jpg", alt: "Provence bedroom provincial styling", title: "Bed & seating", meta: "Ground floor · provincial" },
  { room: "living", src: "assets/photos/optimized/interior-lounge-2.jpg", alt: "Living room with L-shaped sofa and chandelier", title: "Main lounge", meta: "Ground floor · open plan" },
  { room: "living", src: "assets/photos/optimized/interior-lounge.jpg", alt: "Living room with rustic beams", title: "Lounge & TV", meta: "Ground floor · beams" },
  { room: "living", src: "assets/photos/optimized/interior-dining.jpg", alt: "Dining area with wood stove", title: "Dining & stove", meta: "Ground floor · shared space" },
  { room: "living", src: "assets/photos/optimized/interior-floating-staircase.jpg", alt: "Floating wooden staircase", title: "Floating staircase", meta: "Ground floor · 2025 photo" },
  { room: "garden-room", src: "assets/photos/optimized/garden-room-piano-pool-view.jpg", alt: "Garden room piano with pool view", title: "Piano & pool view", meta: "Ground floor · garden room" },
  { room: "garden-room", src: "assets/photos/optimized/garden-room-lounge.jpg", alt: "Garden room papasan chair overlooking pool", title: "Papasan lounge", meta: "Ground floor · pool access" },
  { room: "garden-room", src: "assets/photos/optimized/garden-room-console-flowers.jpg", alt: "Garden room console with flowers", title: "Floral console", meta: "Ground floor · decor" },
  { room: "bathrooms", src: "assets/photos/optimized/upstairs-bathroom.jpg", alt: "Upstairs spa bathroom stone wall shower", title: "Upstairs bathroom", meta: "Loft · stone wall" },
  { room: "bathrooms", src: "assets/photos/optimized/upstairs-bathrom-2.jpg", alt: "Upstairs bathroom stone vanity", title: "Stone vanity", meta: "Loft · live-edge wood" },
  { room: "bathrooms", src: "assets/photos/optimized/ground-floor-bathroom.jpg", alt: "Ground floor bathroom double vanity", title: "Double vanity", meta: "Ground floor · LED shower" },
  { room: "bathrooms", src: "assets/photos/optimized/photo-bathroom-interior-shower-led-niches.jpg", alt: "Ground floor shower LED niches", title: "LED shower", meta: "Ground floor · rainfall" },
  { room: "kitchen", src: "assets/photos/optimized/kitchen-corner-wide.jpg", alt: "Kitchen blue-grey cabinets wide view", title: "Kitchen overview", meta: "Ground floor · equipped" },
  { room: "kitchen", src: "assets/photos/optimized/photo-kitchen-light-blue-cabinets-wood-countertop.jpg", alt: "Kitchen marble backsplash and wood counter", title: "Counter detail", meta: "Ground floor · marble" }
];

window.GALLERY_ROOMS = [
  { id: "all", label: "All photos" },
  { id: "exterior", label: "Pool & garden" },
  { id: "barcelona", label: "Barcelona suite" },
  { id: "asian", label: "Asian room" },
  { id: "provance", label: "Provence bedroom" },
  { id: "living", label: "Living room" },
  { id: "garden-room", label: "Garden room" },
  { id: "bathrooms", label: "Bathrooms" },
  { id: "kitchen", label: "Kitchen" }
];
