'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {transform,pageUrl,setAttr,cleanSchema}=require('./build-site.cjs');
assert.equal(pageUrl('index.html'),'https://villa-augflor.com/');
assert.equal(pageUrl('fr/index.html'),'https://villa-augflor.com/fr/');
assert.equal(pageUrl('rates.html'),'https://villa-augflor.com/rates.html');
assert.equal((setAttr('<img width="10" src="x.jpg">','width',25).match(/width=/g)||[]).length,1);
const input='<!doctype html><html lang="en"><head><title>Old</title><meta name="description" content="Old"><link rel="canonical" href="old"><script type="application/ld+json">{"@type":"ReservationAction"}</script></head><body><nav>Home</nav><section class="hero"><div class="hero-img hi4 lazy-bg" data-bg="assets/a.jpg"></div><h1>Summer 2026</h1><p class="hero-price-line">From €420/night</p></section><section id="existing"><h2>About</h2></section><!-- OFFERS-LD:START --><script type="application/ld+json">{"availabilityStarts":"2026-07-01"}</script><!-- OFFERS-LD:END --><!-- OPEN-WEEKS:START -->Fake open dates<!-- OPEN-WEEKS:END --></body></html>';
const html=transform(input,'index.html').html;
assert(html.includes('Summer 2027'));
assert(!html.includes('Fake open dates'));
assert(!html.includes('From €420/night'));
assert(!html.includes('ReservationAction'));
assert(html.includes('id="existing"'));
assert.equal((html.match(/rel="canonical"/g)||[]).length,1);
assert.equal((html.match(/hreflang=/g)||[]).length,5);
assert(html.indexOf('va-season-notice')>html.indexOf('</section>'));
for(const f of ['calendar-widget.js','enquiry-form.js'])new vm.Script(fs.readFileSync(require('node:path').join(__dirname,f),'utf8'));
const cal=fs.readFileSync(require('node:path').join(__dirname,'calendar-widget.js'),'utf8');
assert(!/Math\.random|mockBusy|Fully booked|Open — enquire/.test(cal));
const form=fs.readFileSync(require('node:path').join(__dirname,'enquiry-form.js'),'utf8');
assert(form.includes('Number(inputs.adults.value)+Number(inputs.children.value)>6'));
assert(form.includes('inputs.checkout.value<=inputs.checkin.value'));
assert(!/localStorage|sessionStorage|gtag\(/.test(form));
console.log('Technical regression tests passed (URL, schema cleanup, season copy, canonical/hreflang, layout IDs, calendar safety and form guards).');
