/* Photo tour and direct-enquiry handoff. No invented availability or prices. */
(function(){'use strict';
const modal=document.querySelector('.photo-viewer');
let current=0,photos=[],returnFocus;
function visiblePhotos(){return Array.from(document.querySelectorAll('a[data-photo]')).filter(a=>!a.closest('[hidden]'));}
function show(i){current=(i+photos.length)%photos.length;const a=photos[current],img=a.querySelector('img');const large=modal.querySelector('[data-photo-image]');large.src=a.href;large.alt=img.alt;modal.querySelector('[data-photo-caption]').textContent=a.dataset.caption||img.alt;modal.querySelector('[data-photo-counter]').textContent=(current+1)+' / '+photos.length;}
if(modal){document.querySelectorAll('a[data-photo]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey||e.shiftKey)return;e.preventDefault();photos=visiblePhotos();returnFocus=a;show(photos.indexOf(a));modal.showModal();document.body.style.overflow='hidden';modal.querySelector('[data-photo-close]').focus();}));modal.querySelector('[data-photo-close]').addEventListener('click',()=>modal.close());modal.querySelector('[data-photo-prev]').addEventListener('click',()=>show(current-1));modal.querySelector('[data-photo-next]').addEventListener('click',()=>show(current+1));modal.addEventListener('close',()=>{document.body.style.overflow='';returnFocus?.focus();});modal.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();show(current+1);}if(e.key==='ArrowLeft'){e.preventDefault();show(current-1);}});let touchX=0;modal.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;},{passive:true});modal.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>60)show(current+(dx<0?1:-1));},{passive:true});}
const filters=document.querySelectorAll('[data-filter]');function filter(category){filters.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===category)));document.querySelectorAll('[data-category]').forEach(s=>s.hidden=category!=='all'&&s.dataset.category!==category);}
filters.forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));
const form=document.querySelector('[data-stay-form]');if(!form)return;
const fields=form.elements,status=form.querySelector('[data-stay-status]');const d={};new Intl.DateTimeFormat('en',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).forEach(p=>d[p.type]=p.value);const today=d.year+'-'+d.month+'-'+d.day;fields.arrival.min=today;fields.departure.min=today;
function validate(){fields.arrival.setCustomValidity(fields.arrival.value<today?'Please choose a future arrival date.':'');fields.departure.setCustomValidity(fields.departure.value<=fields.arrival.value?'Departure must be after arrival.':'');const n=Number(fields.guests.value);fields.guests.setCustomValidity(!Number.isInteger(n)||n<1||n>6?'Please select 1 to 6 guests.':'');return form.reportValidity();}
form.addEventListener('input',()=>{fields.arrival.setCustomValidity('');fields.departure.setCustomValidity('');fields.guests.setCustomValidity('');status.textContent='';});fields.arrival.addEventListener('change',()=>{if(fields.arrival.value){const date=new Date(fields.arrival.value+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+1);fields.departure.min=date.toISOString().slice(0,10);}});
form.addEventListener('submit',e=>{e.preventDefault();if(!validate())return;const channel=e.submitter?.value==='email'?'email':'whatsapp';const text='Hi Lana, please check Villa Augflor for:\nArrival: '+fields.arrival.value+'\nDeparture: '+fields.departure.value+'\nGuests (including children): '+fields.guests.value+'\n'+(fields.notes.value?'\n'+fields.notes.value+'\n':'')+'\nPlease confirm availability and send a full written quote.';window.dispatchEvent(new CustomEvent('villa-enquiry-handoff',{detail:{channel}}));status.textContent='Your enquiry is ready. Review and send it in '+(channel==='email'?'your email app.':'WhatsApp.');location.href=channel==='email'?'mailto:villa.augflor@gmail.com?subject='+encodeURIComponent('Villa Augflor enquiry — '+fields.arrival.value)+'&body='+encodeURIComponent(text):'https://wa.me/33623777333?text='+encodeURIComponent(text);});
})();
